### ISSUE TITLE
Keep info about active tab item

### ISSUE THREAD

**Issue by ashbaldry** [Appsilon/shiny.semantic#108]
Similar to https://github.com/Appsilon/semantic.dashboard/issues/93, it would be good to be able to reference the active item in `tabset()` within the server function, much like `tabsetPanel()` in standard shiny.

**Comment by dokato** [comment]
@ashbaldry True. We'll increase the priority of that, however, of course, PRs are welcome :)

**Comment by ashbaldry** [comment]
@dokato I have got part of it working, it takes the tab-name on every time the tab changes except on the initialisation of the shiny app. I've tried onFirstLoad but didn't seem to work. Change is available [here](/ashbaldry/shiny.semantic/tree/feature/active-tab)

**Comment by krystian8207** [comment]
Hi @ashbaldry 
The feature was added in #132 
Thank you for contributing. Your code required a few changes, please check the PR to find out the correct solution.

**Comment by ashbaldry** [comment]
Ah, thanks @krystian8207, much neater! Will remember the initialisation bit for the future :)
