### ISSUE TITLE
Merge conflicts in docs/index.html not completely resolved

### ISSUE THREAD

**Issue by gadenbuie** [Appsilon/shiny.semantic#122]
It appears that there are still a few lingering merge conflicts in `docs/index.html` that weren't entirely resolved in https://github.com/Appsilon/shiny.semantic/commit/6335193a04ff9fb5e906cef6dd5485fa92e7812e, for example:

https://github.com/Appsilon/shiny.semantic/blob/0b0b98b01d3344591ae288d1b4916c293d1c495c/docs/index.html#L141-L147

**Comment by dokato** [comment]
Thanks @gadenbuie for reporting this. We're on this now #123 ;)
