### ISSUE TITLE
Listing semantic library version

### ISSUE THREAD

**Issue by nteetor** [Appsilon/shiny.semantic#139]
Is there an official listing of the Semantic UI version used by shiny.semantic?

**Comment by dokato** [comment]
Hi @nteetor . By default shiny.semantic loads Semantic UI 2.3.1 from our CDN. But you can also customize it with your local semantic installation using:
```r
options(shiny.custom.semantic = "styles/")
```
where `styles/` is a folder contating semantic components: css, js, fonts etc. I hope it helps!

**Comment by nteetor** [comment]
Great, thank you very much.
