### ISSUE TITLE
I want below component source code please help me

### ISSUE THREAD

**Issue by karthees89** [Appsilon/shiny.semantic#140]
![image](https://user-images.githubusercontent.com/52206594/61872986-59a08c00-af02-11e9-93b9-b89babc42a74.png)

**Comment by ashbaldry** [comment]
Take a look at the after code in [readme_assets/ui_demo.R](https://github.com/Appsilon/shiny.semantic/blob/5aa1416ed50d933870ea5c885ff3780519fb6beb/readme_assets/ui_demo.R)
