### ISSUE TITLE
Feature request: update_search_selection_choices

### ISSUE THREAD

**Issue by fmusili** [Appsilon/shiny.semantic#141]
I wish to update the selected choice interactively on the shiny dashboard server side according to leaflet map click. Previously i have used  updateSelectInput() to update selectInput(). Is there an option to update search_selection_choices()  or how can i hack it?

**Comment by dokato** [comment]
Hi @fmusili. It's not entirely clear to me what you want to achieve. Could you provide a small example with a description of expected behaviour after the leaflet map click?

**Comment by fmusili** [comment]
I have a leaflet map with country boundaries. The first option is to select the country from search_selection_choices() dropdown list and the leaflet map zooms to the specific country. I want to add another option where the user can click on the map and after leaflet zooms into the clicked country, the search_selection_choices() automatically selects  clicked country from the dropdown .

I hope that's more clear.

**Comment by dokato** [comment]
@fmusili check `update_dropdown` now
