### ISSUE TITLE
changing theme programmatically

### ISSUE THREAD

**Issue by systats** [Appsilon/shiny.semantic#148]
Hi - what is the easiest way to change between two themes programmatically? There is a boostrap example of [theme selector](https://shiny.rstudio.com/gallery/shiny-theme-selector.html) that accomplishes exactly that. Maybe you have an idea how to implement it?

**Comment by dokato** [comment]
Hi @systats sorry for the huge delay with it. We've been working hard on releasing version `0.3.0` recently. Now that we have this out of the desk, we will put this into roadmap for next iteration. Thanks for the suggestion.

**Comment by krystian8207** [comment]
@systats We've added `theme_selector`. Please check the latest package version at `develop` branch.
