### ISSUE TITLE
How we handle font sizes?

### ISSUE THREAD

**Issue by dokato** [Appsilon/shiny.semantic#186]
We have 2 options. Now we have text formatting, eg. "small", "medium", "huge" etc, but...

@krystian8207 has a fair point here.

> We need to rethink the way sizes are used in shiny.semantic. For me using integers is much easier as I don't need to remember size codes. 

I think we need to test that in battle and see what users prefer.

**Comment by jchojna** [comment]
As Marek said, it seems to be more natural to use pre-defined classes to determine font sizes, so I would stick with it and make font classes description more visible for the user in the documentation. Regarding @krystian8207  doubts, I could suggests taking a look at for example AutoKey (for Linux) and setup some phrases to output specific text classes on the fly while development process. So for example:

**Comment by dokato** [comment]
Contant `FOMANTIC_FONT_SIZES` is added now. We can introduce some check if the size is good, but imho it requires other issue.
