### ISSUE TITLE
[ENH] progress bar

### ISSUE THREAD

**Issue by dokato** [Appsilon/shiny.semantic#199]
As it is in shiny.

Using this: https://fomantic-ui.com/modules/progress.html 

Test check, this works:
```r
library(shiny)
library(shiny.semantic)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    withProgress(message = 'Calculation in progress',
                 detail = 'This may take a while...', value = 0, {
      for (i in 1:15) {
        incProgress(1/15)
        Sys.sleep(0.25)
      }
    })
    plot(cars)
  })
}

shinyApp(ui, server)
```

**Comment by ashbaldry** [comment]
Hey, 
I've had a go at this the last couple of days, and have made some progress so thought would share. `withProgress` and `incProgress` aren't enabled yet, but I get a progress bar that opens, increases, and then closes using the functionality below. Will try and continue with this but WIP is available in my 
[progress](https://github.com/ashbaldry/shiny.semantic/tree/progress) branch.
```r
library(shiny)
library(shiny.semantic)

ui <- semanticPage(
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    
    progress <- Progress$new(session, min=0, max=15)
    on.exit(progress$close())
    
    progress$set(message = 'Calculation in progress',
                 detail = 'This may take a while...')
    
    for (i in 1:15) {
      progress$set(value = i)
      Sys.sleep(0.5)
    }
    plot(cars)
  })
}

shinyApp(ui, server)
```

**Comment by dokato** [comment]
@ashbaldry splendid! thanks a lot! Recently we decided that we want to have also wrappers that would be as much compatible with `shiny` syntax as possible with available extensions (usually in `snake_case`) that allow for more fomantic-like behaviour.

BTW maybe you noticed that there's been much more going on in the package recently. It's because we set a goal to move up to the next level in version `0.3.5`. You can watch the progress here: https://github.com/Appsilon/shiny.semantic/projects/1 any help would be highly appreciated, just LMK :)

**Comment by ashbaldry** [comment]
That's really cool! Feels like eventually you'll be able to just put `library(shiny.semantic)` after loading shiny and it'll convert with no issues.

I've tried tonight and it does work with the original test too. The only thing I cannot easily include is the detail parameter, as the Fomantic progress bar only includes one message component. If you think it's necessary I'll find a way to add the detail in.
