### ISSUE TITLE
add styleguide

### ISSUE THREAD

**Issue by olgamie** [Appsilon/shiny.semantic#212]
- [x] wrapper follow shiny camelcase syntaxing
- [x] `uiname` is okay for frontend/ static items
- [x] internal: snake case `my_button` for input elements
- [x] const: `CONST`
- [x] use explicit calls eg. `shiny::div`, avoid `@imports`

**Comment by krystian8207** [comment]
I added short reasoning in internal documents. The general proposition is:

- Remove ui prefix from UI static functions.
- Add _input to all input functions.
- Consequently use camel_case (this way we can create shiny consistent wrappers but also shiny.semantic generalizations)
- Rethink the names of all existing functions and make sure they’ll not confuse package users.
- Remove useless functions or make them internal ones.
- (Optional) Move simple ui static functions to a common list.

**Comment by dokato** [comment]
styleguide has been added, we're now making our code coherent with it
