### ISSUE TITLE
Add examples of uiicons, remove uicheckbox

### ISSUE THREAD

**Issue by olgamie** [Appsilon/shiny.semantic#219]
Add examples of how to create different icons.

Remove uicheckbox and only keep simple_checkbox. Having both is confusing and doesn't create any additional value to the user.

**Comment by dokato** [comment]
here look at #223 some of the things might have been fixed already, or renamed at least... i suggest waiting with it once it's merged in

**Comment by krystian8207** [comment]
@olgamie is it already done?
