### ISSUE TITLE
Feature request: Add support for themes from http://semantic-ui-forest.com/

### ISSUE THREAD

**Issue by filipstachura** [Appsilon/shiny.semantic#23]
Semantic-UI-Forest is a collection of design, themes and templates for Semantic-UI: http://semantic-ui-forest.com/

We want to add support for these to allow seamless change between themes in the Shiny app.

Acceptance criteria:
- backward compatibility - no need to add anything to use default theme
- single drop-in - theme should be configured in one place
- loading only stylesheets for specified theme in the app.

**Comment by KrzysztofWrobel** [comment]
+1
