### ISSUE TITLE
rating example doesn't run 

### ISSUE THREAD

**Issue by dietrichson** [Appsilon/shiny.semantic#236]
I get
Error in rating_input(name = "rating", label = "", value = 0, max = 5,  : 
  could not find function "rating_input" 

if I switch to "rating" the code runs. Installed from github, but not latest CRAN.

I suspect you just update the function name like I did.

**Comment by dietrichson** [comment]
This is the file I sourced:

https://github.com/Appsilon/shiny.semantic/blob/develop/examples/rating/app.R

**Comment by dokato** [comment]
Thanks @dietrichson for reporting this. Actually we decided recently to keep syntax the way, that all the active elements have `_input` suffix and all static UI elements are just name of the generated object. It's like in standard shiny. So if you update the latest version from repo (branch `develop`) it should be `rating_input` now. Sorry for not introducing backward compatibility, but hopefully the new release will be nice, clean and stable ;) 
Expect the new version `0.3.5` on CRAN towards the end of August.
