### ISSUE TITLE
Add an option to configure text input label position

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/shiny.semantic#261]
### Problem
The label of text input appears either to the left of the input box or above it depending on the label length and horizontal space available for the whole element. This can lead to unpleasant inconsistencies when multiple text inputs are used.

Small, fixed width:
![flow_layout](https://user-images.githubusercontent.com/10000651/89782940-6c3e3100-db16-11ea-9502-49949df894e1.png)

Slightly larger width:
![flow_layout_broken](https://user-images.githubusercontent.com/10000651/89782942-6d6f5e00-db16-11ea-9847-1a3f497e38f6.png)

### Proposed solution
Use an additional parameter for text inputs so the user can choose label placement: next to the input box, above, auto.

**Comment by esraay** [comment]
It will be fixed with in #235
