### ISSUE TITLE
register_search

### ISSUE THREAD

**Issue by aavanesy** [Appsilon/shiny.semantic#269]
Hi,

Could you please provide any example whatsoever of how this function works?
I am unable to find any information on this function and am unable to use it myself.

It generates a link such as: session/f8be969bd8f510ca10e5f9fb4022ed24/dataobj/search_api?w=3c9c8d80&nonce=ef97e0fd0ab35d15

What do I do next?

Is is possible to obtain my data using GET?

Thank you a lot!

**Comment by krystian8207** [comment]
Hi @aavanesy 

I added an example to `register_search` docs: #276 

Please also take a look at this example: https://github.com/Appsilon/shiny.semantic/blob/76ebd9127cea3039972ea316569f02d3299091a6/examples/search_selection/api_choices.R
You may find here how to create search input connected with the registered API.

**Comment by dokato** [comment]
It's added to our examples now.
