### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by jcheng5** [Appsilon/shiny.semantic#270]
Just wanted to let you know that the link to https://demo.appsilon.ai/semantic/ on the README is returning a 404. Thanks!

**Comment by dokato** [comment]
thank you @jcheng5 for reporting that, recently we moved our demos to a new location: https://demo.appsilon.ai/apps/semantic/ and embarrassingly forgot to change the alias

**Comment by DamianBudelewski** [comment]
thanks for reporting that, I added the alias and https://demo.appsilon.ai/semantic is working correctly now.

**Comment by jcheng5** [comment]
Thanks! Two more links on the homepage, "churn analytics" and "fraud detection" are still broken--adding a trailing slash makes them redirect correctly.

**Comment by DamianBudelewski** [comment]
Good point. Now it works for demo.appsilon.ai/churn and demo.appsilon.ai/churn/ (with trailing slash).
