### ISSUE TITLE
Add fileInput widget

### ISSUE THREAD

**Issue by mdubel** [Appsilon/shiny.semantic#294]
With semantic the default Shiny fileInput is working but the styling is broken. There is no other way to include fileInput. It would be ok to make default one looking good.

**Comment by ashbaldry** [comment]
Hey,
I'm having a go at this, here a couple of screenshots of what I have so far, let me know your thoughts 😃 

![image](https://user-images.githubusercontent.com/8420419/100742118-2a413f80-33d2-11eb-8e38-839640801ea3.png)
![image](https://user-images.githubusercontent.com/8420419/100742151-39c08880-33d2-11eb-8f2a-294cd5cc1e7e.png)
