### ISSUE TITLE
selectInput doesn't recognize a single value being selected

### ISSUE THREAD

**Issue by DamianRodziewicz** [Appsilon/shiny.semantic#308]
Repro - run the following application:

```
library(shiny)
library(shiny.semantic)

ui <- semanticPage(
  uiOutput("test")
)

server <- function(input, output) {
  output$test <- renderUI({
    shiny.semantic::selectInput(
      inputId = "selected",
      label = NULL,
      choices =  c("a", "b", "c"),
      selected = c("a"),
      multiple = TRUE
    )
  })
}

shinyApp(ui = ui, server = server)
```

Expected result - "a" should be selected

Observed result - no item is selected

Doesn't work when writing `selected = "a"` either.

**Comment by dokato** [comment]
Are you sure, you are using the latest version: `0.4.0`? This works for me:

<img width="317" alt="Screenshot 2020-09-14 at 18 31 31" src="https://user-images.githubusercontent.com/4547289/93118717-9906da80-f6b8-11ea-8fc1-50288d4cf83e.png">

```r
server <- function(input, output) {
  output$test <- renderUI({
    shiny.semantic::selectInput(
      inputId = "selected",
      label = NULL,
      choices =  c("a", "b", "c"),
      selected = c("a", "b"),
      multiple = TRUE
    )
  })
}
```

**Comment by DamianRodziewicz** [comment]
@dokato yes I'm running `0.4.0` it does work for multiple values selected, however, it does not work for **one** value selected. (`selected = c("a")`)
