### ISSUE TITLE
Is there a way to update the selected tab from `tabset()`?

### ISSUE THREAD

**Issue by daattali** [Appsilon/shiny.semantic#323]
When using a tabset, the `updateTabsetPanel()` doesn't work with it. The package does not provide an alternative. Is there a standard way to achieve this? Perhaps a `shiny.semantic::updateTabset()` function should be added?

**Comment by dokato** [comment]
Hi @daattali , this should work now. Thanks for suggestion and see this example:
https://github.com/Appsilon/shiny.semantic/blob/develop/examples/tabset/app.R
If you encounter trobules, feel free to reopen.
