### ISSUE TITLE
Some UI overlapping issues

### ISSUE THREAD

**Issue by shahreyar-abeer** [Appsilon/shiny.semantic#329]
Please have a look at the attached screenshots.
They should be self-sufficient to describe the issue.

![image](https://user-images.githubusercontent.com/20732893/102175117-182ec900-3ec9-11eb-92f7-a9c960143ccd.png)

![image](https://user-images.githubusercontent.com/20732893/102175560-f97d0200-3ec9-11eb-8a9b-c342f0e61158.png)

**Comment by dokato** [comment]
This I'm afraid is Fomantic UI issue. Look, I made an experiment with an example from their documentation:

<img width="443" alt="Screenshot 2020-12-30 at 09 41 52" src="https://user-images.githubusercontent.com/4547289/103343209-7a6bfa00-4a83-11eb-9fb8-9a30e6a4b593.png">


`shiny.semantic` is merely a wrapper to Fomantic components. I suggest you report it on their repository: https://github.com/fomantic/fomantic-ui
