### ISSUE TITLE
Bug in updateSelectInput: label is not given a default value, but in shiny label has a default

### ISSUE THREAD

**Issue by daattali** [Appsilon/shiny.semantic#339]
This means that if you have code `updateSelectInput(session, "test", selected = "test"), it works in a shiny app but the moment `shiny.semantic` is loaded it causes a fatal error.

Related to https://github.com/Appsilon/shiny.semantic/issues/328

**Comment by dokato** [comment]
Thanks for reporting that, this should be fixed with #340 now.
