### ISSUE TITLE
Non-Tabular Menu Doesn't Call JS

### ISSUE THREAD

**Issue by ashbaldry** [Appsilon/shiny.semantic#347]
When you change the menu class in `tabset` to something that doesn't include "tabular", the tabs do not switch when clicked. Should it be `.menu.sem`?

https://github.com/Appsilon/shiny.semantic/blob/0bc4903977a88cc8aa7eba842fb83118a70925c6/inst/www/shiny-semantic-tabset.js#L4-L6

**Comment by dokato** [comment]
Thanks for the suggestion, this should be fixed now.
