### ISSUE TITLE
UI Slider Without Custom Labels Breaks

### ISSUE THREAD

**Issue by ashbaldry** [Appsilon/shiny.semantic#351]
When updating #160 I introduced a bug when not including custom labels, we don't need the interpretLabel parameter for standard sliders:

https://github.com/Appsilon/shiny.semantic/blob/1580e385b760fcd85a8b0de2ad22822f3be516fc/inst/www/shiny-semantic-slider.js#L21

**Comment by rolfmblindgren** [comment]
Seems to work now! Thanks!

**Comment by mattapel** [comment]
Hi there
I still have that issue: semantic slider_input fails if min != 0
Shiny-Version: 1.6.0
shiny.semantic 0.4.2


example:
######
library(shiny)
library(shiny.semantic)

ui <- shinyUI(
    semanticPage(
        title = "Slider example",
        tags$br(),
        slider_input("slider", 10, 1, 20, class = "labeled ticked"),
        p("Selected value:"),
        textOutput("slider")
    )
)
server <- shinyServer(function(input, output, session) {
    output$slider <- renderText(input$slider)
})
shinyApp(ui = ui, server = server)
