### ISSUE TITLE
sidebar_layout rendering ui elements incorrectly

### ISSUE THREAD

**Issue by AarshBatra** [Appsilon/shiny.semantic#354]
Hi,

I started with an example from the [documentation page](https://appsilon.github.io/shiny.semantic/articles/intro.html) of **shiny.semantic**  (scroll down and under **built in layouts** look at the last example, right before the **grid templates** section starts).  

First, I simply copied the code into my app file and then I ran the app file. In the output window, the following was rendered:

- The `sidebar_layout`, and its 2 main functions: `sidebar_panel` and `main_panel` are not rendering ui as they should. 
  - Specifically, the output contains all the ui elements stacked one below the other vertically. 
  - So essentially what I get is the **mtcars** dropdown (which should be in the `sidebar_panel`), followed by the **Cards 1 and 2** (horizontally stacked together), followed by the **Histogram**, followed by the **Scatter Plot**. 

Here are the troubleshooting steps that I have taken to try fix this, but none of these worked (which is why I am filing this issue):

- I used the `package::function` notation everywhere in the above example, so as to avoid getting clashes between packages `shiny` and `shiny.semantic` (as mentioned  in issue #328). Besides, I only used standard HTML elements from `shiny` package (to avoid any clashes with the `shiny.semantic` package) as recommended in the [FAQ's](https://appsilon.github.io/shiny.semantic/articles/basics.html) in the help pages.
- I installed the latest release of `shiny.semantic` using `remotes::install_github("Appsilon/shiny.semantic@develop")`.
- I made sure that `suppress_bootstrap = TRUE` (which is the default).
- I tried all the troubleshooting steps mentioned in the shiny.semantic [documentation page](https://github.com/Appsilon/shiny.semantic). Specifically:
   - My R language environment is up to date `R version 4.0.4 (2021-02-15)`.
   - R Studio is up to date.
   - I made sure that `suppress_bootstrap = TRUE` (which is the default).
   - I installed specific dependent library versions (`version: 0.14.2`) as mentioned in the documentation.
        - **Note: Update Documentation**: 
            - I noticed that the [documentation page](https://github.com/Appsilon/shiny.semantic) mentions the following `install.packages("shiny", version='0.14.2.9001')` to install specific dependent library versions. But, this does not work as R installs the latest version of shiny irrespective of the `version` mentioned in the `install.packages`. This might be due to the fact that `version` is not a valid argument for the function `install.packages`.
            -  The above function in the documentation can be replaced with the following: `devtools::install_version("shiny", version = "0.14.2", repos = "http://cran.us.r-project.org")`.
    - I looked into the [issues page](https://github.com/fomantic/Fomantic-UI/issues?page=1&q=is%3Aissue+is%3Aopen) at the [Semantic UI](https://github.com/fomantic/Fomantic-UI) repository, but none seems to address this issue.

Also, I am facing similar issues as the above in the `semantic.dashboard` library. But, when I use the `grid_template()` functionality within `semanticPage()` ui elements render correctly.

I may be missing something obvious. But I have gone through a lot of troubleshooting. Can anyone tell what might be the issue behind this?

Many Thanks, 
Aarsh

**Comment by dokato** [comment]
@AarshBatra thank you for reporting that. PR #355 should fix that.

**Comment by AarshBatra** [comment]
> @AarshBatra thank you for reporting that. PR #355 should fix that.

# @dokato, @jchojna that sounds great! Thanks. I will install the latest version of shiny.semantic and try out the sidebar_layout functionality.

**Comment by AarshBatra** [comment]
> > @AarshBatra thank you for reporting that. PR #355 should fix that.
> 
> # @dokato, @jchojna that sounds great! Thanks. I will install the latest version of shiny.semantic and try out the sidebar_layout functionality.

@dokato, @jchojna that sounds great! Thanks. I will install the latest version of shiny.semantic and try out the sidebar_layout functionality.

**Comment by AarshBatra** [comment]
> > @AarshBatra thank you for reporting that. PR #355 should fix that.
> 
@dokato, @jchojna that sounds great! Thanks. I will install the latest version of shiny.semantic and try out the sidebar_layout functionality.

**Comment by dokato** [comment]
great, feel free to reopem if needed
