### ISSUE TITLE
UI slider input (still) fails when min != 0

### ISSUE THREAD

**Issue by mattapel** [Appsilon/shiny.semantic#374]
#my shiny version: 1.6.0
#my semantic version 0.4.2
# both in RStudio browser and Chrome

library(shiny)
library(shiny.semantic)

ui <- shinyUI(
semanticPage(
title = "Slider example",
tags$br(),
slider_input("slider", 10, 1, 20, class = "labeled ticked"),
p("Selected value:"),
textOutput("slider")
)
)
server <- shinyServer(function(input, output, session) {
output$slider <- renderText(input$slider)
})
shinyApp(ui = ui, server = server)

**Comment by ashbaldry** [comment]
The fix for #362 isn't on CRAN yet. If you install the development version `remotes::install_github("Appsilon/shiny.semantic@develop")` it should work.
