### ISSUE TITLE
Feature Request: disable easy close for populated modals

### ISSUE THREAD

**Issue by EnzleAnalytics** [Appsilon/shiny.semantic#376]
Hello! Not necessarily anything wrong with the current modals but I was wondering if there was any way to disable closing a semantic modal by clicking outside of it (or the esc key)? I'm trying to ensure a modal stays up on a screen until an input is put into the text bar (see pic). If a user clicks the "go back" button without imputing an ID, it simply repopulates the modal; I'm looking for a way to do the same for when a user clicks outside the modal.

I know there is a standard 'shinyDialog' that could do something similar here, but I wanted to at least pose the question. 

Thanks!

![image](https://user-images.githubusercontent.com/64592677/125077858-d345cc00-e07e-11eb-9373-da1e44fb7022.png)

**Comment by federiva** [comment]
Hi @EnzleAnalytics! Thanks for reaching! 
Can you provide a reproducible code example for the modal you have there? 
Also, can you test the following example to see if this usage cover your use case?
Thanks!
```

ui <- function() {
  shinyUI(
    semanticPage(
      actionButton("show", "Show modal dialog")
    )
  )
}

server = function(input, output) {
  observeEvent(input$show, {
    create_modal(modal(
      id = "simple-modal",
      title = "Important message",
      header = list("!!!", style = "background: lightcoral"),
      content = list(style = "background: lightblue",
                     `data-custom` = "value", "This is an important message!"),
      p("This is also part of the content!")
    ))
  })
}
shinyApp(ui, server)

```

**Comment by ashbaldry** [comment]
Hi @EnzleAnalytics,

I think what you are looking for is to add `settings = list(c("closable", "false"))` into `modal`. This will prevent the modal closing when clicking outside.

**Comment by scizmeli** [comment]
Closing this issue as there was no feedback. Feel free to reopen in case there is need to follow up.
