### ISSUE TITLE
semantic_DT options doesn't work[Bug]: 

### ISSUE THREAD

**Issue by ugurdar** [Appsilon/shiny.semantic#417]
Hi,

I'm trying to right justify the text in the datatable, but I can't do it even though I define it in options.

I can use ```formatStyle('column',` textAlign = 'center') ``` but it affects only column body and not the header.
```
if (interactive()){
  library(shiny)
  library(shiny.semantic)
  
  ui <- semanticPage(
    semantic_DTOutput("table")
  )
  server <- function(input, output, session) {
    output$table <- DT::renderDataTable(
      semantic_DT(iris,
                  options = list(
                    columnDefs = list(
                      list(className = 'dt-right', targets = 1:3)
                      )
                    )
                  )
    )
  }
  shinyApp(ui, server)
}
```

**Comment by esraay** [comment]
Hi @ugurdar, the class name you have provided is not supported by fomanticUI. For your example, you can update the class name with "right aligned". To explore all features of fomanticUI tables you can check out https://fomantic-ui.com/collections/table.html

Also, we are progressing with some work about style and class arguments for semantic_DT in #409, after this work merges you will be able to use this 'dt-right' class without fomantic UI classes.
