### ISSUE TITLE
[Feature]: Enable placeholder in `numeric_input`

### ISSUE THREAD

**Issue by osenan** [Appsilon/shiny.semantic#428]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Right now argument `placeholder` is not used in a `numeric_input` altough it is included as an argument.

The following example app does not have a placeholder in the input when the `value` is `NULL`:
```
library(shiny)
library(shiny.semantic)
ui <- semanticPage(
  numeric_input("ex", "Select number", value = 3, placeholder = "type value")
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

### Problem

In some contexts users might benefit from viewing a placeholder in a numeric_input

### Proposed Solution

Including `placeholder` in the input tag and changing the checks

### Alternatives Considered

A `text_input` could be used with current code

**Comment by shyamtawli** [comment]
Hey @osenan I want to contribute but can you guide me more?

**Comment by osenan** [comment]
Thanks @shyamtawli this issue has been already solved. Nevertheless, we appreciate your offer to contribute. Remeber you can colaborate by solving other open issues or requesting features that you consider interesting.

Best Regards,
Oriol
