### ISSUE TITLE
[Bug]: CSS stylesheet broken

### ISSUE THREAD

**Issue by nickgrealy** [Appsilon/shiny.semantic#434]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

latest

### Platform and OS Version

macOS

### Existing Issues

#88

### What happened?

A CDN resource is no longer available - 404 not found.

The CSS file is missing: https://d335w9rbwpvuxm.cloudfront.net/2.8.3/semantic.min.css

Note: The JS file however, DOES exist: https://d335w9rbwpvuxm.cloudfront.net/2.8.3/semantic.min.js

**UPDATE:** JS file now missing too: https://d335w9rbwpvuxm.cloudfront.net/2.8.3/semantic.min.js

### Steps to reproduce

I'm currently maintaining a Shiny project on behalf of a client - this has started occurring to an app currently in production.

### Expected behavior

No changes - that the CDN would continue to provide the file.

### Additional Information

I can't find any reference to `d335w9rbwpvuxm` or `semantic.min.css` in the source code... which I assume means it's a dynamic import?

As a project maintainer - this makes it very difficult to troubleshoot. 

Secondly, self hosting the files should be the default. I realise there are [performance implications](https://github.com/Appsilon/shiny.semantic/issues/88#issuecomment-387523002), but introducing an external dependency which requires internet connectivity is not ideal.

I can see from [this config page](https://rdrr.io/github/Appsilon/shiny.semantic/src/R/semanticPage.R), that we have an option to self host the files using `shiny.custom.semantic.cdn` or even `shiny.semantic.local`... 

**Can someone point me to where I can grab the files and set this up please?**

- https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.4/semantic.min.css
- https://www.unpkg.com/semantic-ui@2.5.0/dist/semantic.min.css

**Comment by vibalre** [comment]
Working on a PR to fix this issue, we are planning to use library 2.9.2 to solve this.

* https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2

**Comment by nickgrealy** [comment]
Thanks @vibalre , confirming that workaround is working.

For future self - here's the dockerfile changes.

```Dockerfile
# overwrite config
RUN echo "local(options(shiny.port = 3838, shiny.host = '0.0.0.0', shiny.custom.semantic.cdn = 'https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2'))" > /usr/lib/R/etc/Rprofile.site
```

**Comment by nickgrealy** [comment]
Thanks @jakubnowicki.

I think I'll continue to use self hosted going forwards.
