### ISSUE TITLE
Post Code for Demo Applications

### ISSUE THREAD

**Issue by benjaminrobinson** [Appsilon/shiny.semantic#46]
Would it be possible on GitHub to post the code behind the demo apps that have been built using shiny.semantic?  I learn better from having the full app to see how things come together and allows me to repurpose code to build and play with the code and how I could leverage it to build some of my own cool things.  Thanks!

http://demo.appsilondatascience.com/shiny.semantic/churn/

**Comment by filipstachura** [comment]
Hi Benjamin,

we are working on something similar right now. We expect to have a new demo ready early January.

Best,
Filip

**Comment by systats** [comment]
Sound great!

**Comment by dokato** [comment]
Hi @benjaminrobinson , please take a look at our new `semantic.dashboard` package: https://github.com/Appsilon/semantic.dashboard . It contains many examples with dashboards similar to the churn demo.
