### ISSUE TITLE
div ui card not rendered correctly when using dashboardPage

### ISSUE THREAD

**Issue by markusdumke** [Appsilon/shiny.semantic#61]
I have the following shiny app including multiple tabPanels. In one tabPanel I have a dashboardPage while in the other I want to use ui cards from shiny.semantic. Then the ui card is not rendered correctly.

```
library(shiny)
library(shinydashboard)
library(shiny.semantic)
ui <- fluidPage(
  tabsetPanel(
    tabPanel("shiny.semantic Panel", 
      semanticPage(
        div(class = "ui card", div(class = "content", div(class = "right floated meta", "14h"), 
          img(class = "ui avatar image", src = "http://semantic-ui.com/images/avatar/large/elliot.jpg"), 
          "Elliot"), div(class = "image", img(src = "http://semantic-ui.com/images/wireframe/image.png")), 
          div(class = "content", span(class = "right floated", uiicon("heart outline like"), 
            "17 likes"), uiicon("comment"), "3 comments"), div(class = "extra content", 
              div(class = "ui large transparent left icon input", uiicon("heart ouline"), 
                tags$input(type = "text", placeholder = "Add Comment..."))))
      )
    ),
    tabPanel("Dashboard Panel",
      dashboardPage(
        dashboardHeader(disable = TRUE),
        dashboardSidebar(disable = TRUE),
        dashboardBody(
          infoBox("Box")
        )
      )
    )
  )
)

server <- function(input, output, session) {}

shinyApp(ui, server)

```

`devtools::session_info()`

> 
> ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  setting  value                       
>  version  R version 3.4.3 (2017-11-30)
>  os       Windows >= 8 x64            
>  system   x86_64, mingw32             
>  ui       RStudio                     
>  language (EN)                        
>  collate  English_Germany.1252        
>  tz       Europe/Berlin               
>  date     2018-01-02                  
> 
> ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  package        * version     date       source                                  
>  assertthat       0.2.0       2017-04-11 CRAN (R 3.4.2)                          
>  backports        1.1.1       2017-09-25 CRAN (R 3.4.1)                          
>  cli              1.0.0       2017-12-22 Github (r-lib/cli@ab1c3aa)              
>  clisymbols       1.2.0       2017-05-21 CRAN (R 3.4.3)                          
>  crayon           1.3.4       2017-09-16 CRAN (R 3.4.2)                          
>  desc             1.1.1       2017-08-03 CRAN (R 3.4.2)                          
>  devtools         1.13.3.9000 2017-12-22 Github (hadley/devtools@0bcfd6e)        
>  digest           0.6.13      2017-12-14 CRAN (R 3.4.3)                          
>  htmltools        0.3.6       2017-04-28 CRAN (R 3.4.2)                          
>  htmlwidgets      0.9         2018-01-02 Github (ramnathv/htmlwidgets@18687ee)   
>  httpuv           1.3.5       2017-07-04 CRAN (R 3.4.2)                          
>  jsonlite         1.5         2017-06-01 CRAN (R 3.4.2)                          
>  magrittr         1.5         2014-11-22 CRAN (R 3.4.2)                          
>  memoise          1.1.0       2017-04-21 CRAN (R 3.4.2)                          
>  mime             0.5         2016-07-07 CRAN (R 3.4.1)                          
>  pkgbuild         0.0.0.9000  2017-12-22 Github (r-lib/pkgbuild@ce7f6d1)         
>  pkgload          0.0.0.9000  2017-12-22 Github (r-lib/pkgload@70eaef8)          
>  R6               2.2.2       2017-06-17 CRAN (R 3.4.2)                          
>  Rcpp             0.12.13     2017-09-28 CRAN (R 3.4.2)                          
>  rlang            0.1.6.9000  2018-01-02 Github (tidyverse/rlang@383a1e1)        
>  rprojroot        1.3-1       2017-12-18 CRAN (R 3.4.3)                          
>  rstudioapi       0.7.0-9000  2017-12-22 Github (rstudio/rstudioapi@109e593)     
>  sessioninfo      1.0.1.9000  2017-12-22 Github (r-lib/sessioninfo@c871d01)      
>  shiny          * 1.0.5       2017-08-23 CRAN (R 3.4.2)                          
>  shiny.semantic * 0.1.1       2018-01-02 Github (Appsilon/shiny.semantic@4517c93)
>  shinydashboard * 0.6.1       2017-06-14 CRAN (R 3.4.3)                          
>  testthat         2.0.0       2017-12-13 CRAN (R 3.4.3)                          
>  usethis          1.1.0.9000  2017-12-22 Github (r-lib/usethis@973bcab)          
>  withr            2.1.1       2017-12-19 CRAN (R 3.4.3)                          
>  xtable           1.8-2       2016-02-05 CRAN (R 3.4.2)                          
>  yaml             2.1.16      2017-12-12 CRAN (R 3.4.3)

**Comment by filipstachura** [comment]
Hi @markusdumke !

Thank you for using _shiny.semantic_ 👍 

The package itself does not play well with bootstrap which is default for 

Short term solution: override bootstrap CSS classes with `style="min-height: 0px;"`:
```
div(class = "ui card", div(class = "content", style="min-height: 0px;", div(class = "right floated meta", "14h"), 
                                          img(class = "ui avatar image", src = "http://semantic-ui.com/images/avatar/large/elliot.jpg"), 
                                          "Elliot"), div(class = "image", img(src = "http://semantic-ui.com/images/wireframe/image.png")), 
                   div(class = "content", style="min-height: 0px;", span(class = "right floated", uiicon("heart outline like"), 
                     "17 likes"), uiicon("comment"), "3 comments"), div(class = "extra content", style="min-height: 0px;",
                              div(class = "ui large transparent left icon input", uiicon("heart ouline"), 
                                  tags$input(type = "text", placeholder = "Add Comment...")))))
```

Long term solution: We are working on one line replacement for shinydashboard based on semantic here: https://github.com/Appsilon/semantic.dashboard This is still WIP but we are actively working on this with all standard components already ported to our package (e.g. tabPanel, infoBox, etc.).

Hope this helps!

**Comment by filipstachura** [comment]
Please re-open if anything is unclear. We are going to post update here on beta release of https://github.com/Appsilon/semantic.dashboard.

**Comment by dokato** [comment]
Hi @markusdumke , this is just to let you know that first version of `semantic.dashboard` was published recently and is available on CRAN: https://cran.r-project.org/web/packages/semantic.dashboard/index.html
