### ISSUE TITLE
Enchance tabset to make (suspendWhenHidden = FALSE) non necessary. 

### ISSUE THREAD

**Issue by filipstachura** [Appsilon/shiny.semantic#62]
Please see how we solved https://github.com/Appsilon/semantic.dashboard/issues/48 for reference.

**Comment by filipstachura** [comment]
This is the chunk that need to be fix: https://github.com/Appsilon/shiny.semantic/blob/2aeabdda8adc6a993d09e319224222f1b4ab4aad/R/dsl.R#L230-L234

with https://github.com/Appsilon/semantic.dashboard/pull/55/commits/9218a9809d3b3824b7e0a086de7c4e9802a05ebc

**Comment by krzysiek-frappsilon** [comment]
fixed in #63 @dokato
