### ISSUE TITLE
Sorting in semantic table using shiny

### ISSUE THREAD

**Issue by pandeymanishh** [Appsilon/shiny.semantic#66]
I am playing with semantic tables within shiny and could get most of the variants given here  https://semantic-ui.com/collections/table.html except the sort feature.

I followed the instructions of downloading the tablesort.js and placed it inside www folder and then ran runApp() from the console ,but it still doesn't work, also looked at semantic git for any issues, couldn't find one.

The original code is here : https://github.com/pandeymanishh/shinyknapsack/blob/master/sample.R
Formatting gets messed when pasted here .

Here's the code snippet I am using :

library(shiny)
#devtools::install_github("Appsilon/shiny.semantic")
library(shiny.semantic)
library(shinyjs)

ui <- function() {
  shinyUI(
    semanticPage(
      shinyjs::useShinyjs(),
      tags$head(tags$script(src="tablesort.js")),
      title = "My page",
      suppressDependencies("bootstrap"),
      p(),
      h4("Table with the class 'ui red table'"),
      HTML('<table class="ui red table">
  <thead>
    <tr><th>Food</th>
            <th>Calories</th>
            <th>Protein</th>
            </tr><tbody>
            <tr>
            <td>Apples</td>
            <td>200</td>
            <td>0g</td>
            </tr>
            <tr>
            <td>Orange</td>
            <td>310</td>
            <td>0g</td>
            </tr>
            </tbody>
            </table>'),      
      p(),
      h4("Table with the class 'ui sortable celled table'"),
      HTML('<table class="ui sortable celled table">
  <thead>
    <tr><th>Food</th>
            <th>Calories</th>
            <th>Protein</th>
            </tr><tbody>
            <tr>
            <td>Apples</td>
            <td>200</td>
            <td>0g</td>
            </tr>
            <tr>
            <td>Orange</td>
            <td>310</td>
            <td>0g</td>
            </tr>
            </tbody>
            </table>')
    )
  )
}

server <- shinyServer(function(input, output) {
  runjs("$('table').tablesort();")
} )
shinyApp(ui = ui(), server = server)

Best,
Manish

**Comment by filipstachura** [comment]
Hi @pandeymanishh!

Thanks for your interest in shiny.semantic. Tablesort is not part of semantic and as such won't be available to your app at the startup. I've seen you added a script tag, but I believe you don't have a file available to your app.

Try this on: `tags$head(tags$script(src="https://rawgit.com/kylefox/jquery-tablesort/master/jquery.tablesort.min.js")),` – this should help.

and add `jquery.tablesort.min.js` to your Shiny project when running in production (or use CDN).

Best,
Filip

**Comment by pandeymanishh** [comment]
Thanks Filip for the suggestion, it worked!
I had to change the js file in my code (which was recommended to use on semantics page).
