### ISSUE TITLE
Icons not exported

### ISSUE THREAD

**Issue by systats** [Appsilon/shiny.semantic#81]
Hi Appsilon team,

while working on a social media project I need icons from twitter, facebook, instagram and telegram. But only standard icons like setting, play and pause are available. 

````
follow_buttons <- function(){
  tagList(
    div(class="icon item",
      uiicon("facebook")
    ),
    div(class="icon item",
      uiicon("setting")
    ),
    div(class="icon item",
      uiicon("play")
    ),
    div(class="icon item",
      uiicon("twitter")
    )
  )
}
````
Plugging this function into the dashboard_header function I get that result...

![screenshot 2018-04-21 01 42 19](https://user-images.githubusercontent.com/22753281/39078021-778c1336-4506-11e8-9713-e60aba4d9180.png)

Do you know where the error is caused? Thanks in Advance. Best, Simon

**Comment by dokato** [comment]
Hi @systats it may be due to updated version of SemanticUI. I'll take a look on that soon.

**Comment by systats** [comment]
Thanks for the response. Actually nothing changed. But I use the semantic.dashboard package that builds on shiny.semantic (?) Could that dependency be the reason for the icon errors?

**Comment by dokato** [comment]
Well, I tested it on cran version and it works fine. Could you reinstall the package?
Look at the example below:
``` r
library(shiny)
library(shiny.semantic)

follow_buttons <- function(){
  tagList(
    div(class="icon item",
        uiicon("facebook")
    ),
    div(class="icon item",
        uiicon("setting")
    ),
    div(class="icon item",
        uiicon("play")
    ),
    div(class="icon item",
        uiicon("twitter")
    )
  )
}

ui <- function() {
  shinyUI(
    semanticPage(
      title = "Icon test",
      follow_buttons()
    )
  )
}

server <- shinyServer(function(input, output) {
})

shinyApp(ui = ui(), server = server)
```
Output:
![screen shot 2018-04-25 at 15 39 48](https://user-images.githubusercontent.com/4547289/39253114-033a7ca6-489f-11e8-92a6-52760e640a0e.png)

**Comment by systats** [comment]
Thanks for the double checking. It seems to be my set up, despite I got the cran versions too. Could you figure out where this error stems from?

![bug](https://user-images.githubusercontent.com/22753281/39255842-bcc8c98a-48ad-11e8-94be-932e2d04dcb8.png)

**Comment by systats** [comment]
I tried to upload this example on shinyapps.io, but this error occurred. Could this be related? Thanks for your help!

![screenshot 2018-04-25 18 12 29](https://user-images.githubusercontent.com/22753281/39258598-a622c6e8-48b4-11e8-86c8-ad144d3b52ad.png)

**Comment by dokato** [comment]
Regarding the last one: I think that this might help: `devtools::install_github("Appsilon/shiny.semantic", ref = "cdn-path-fix")`. @systats, could you try it out and let me know?
Maybe it'll help with previous error as well.

**Comment by filipstachura** [comment]
@dokato  the problems with the mismatch in protocols (http/https) might be solved by using URL with `//` protocol. More here: https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by systats** [comment]
Well done people, never looked better! ;)
