### ISSUE TITLE
Feature request: Add modal support to shiny.semantic

### ISSUE THREAD

**Issue by emilmahler** [Appsilon/shiny.semantic#87]
As far as I can see, there is no way to use showModal from Shiny, or a div with class = ui modal. This is a pretty important feature in Shiny apps.

**Comment by dokato** [comment]
Thanks @emilmahler for this suggestion. That's definitely feasible to do and important. Of course PRs are welcome ;)

**Comment by diegollarrull** [comment]
+1  to this request. packages like shinyalert don't seem to work either
