### ISSUE TITLE
Fancy Issue (sticky segment)

### ISSUE THREAD

**Issue by systats** [Appsilon/shiny.semantic#92]
Hi guys,

at the moment i'm asked to build a profile manager. For better usability it would be good if the profile on the right hand side sticks to the view of the user while scrolling down. 

![screenshot 2018-05-26 22 27 16](https://user-images.githubusercontent.com/22753281/40580355-b93f8702-613c-11e8-93a1-cc05df904432.png)

A miminal example ...

```
ui <- function() {
  shinyUI(
    semanticPage(
      div(class = "ui grid",
        div(class ="row",
          div(class = "eight wide column",
            div(class = "ui segment",
              purrr::map(1:100, ~ br()),
              "End of the page ..."
            )
          ),
          div(class = "eight wide column",
            div(class = "ui secondary segment",
                "Profile - How to make this segment sticky?"
            )
          )
        )  
      )
    )
  )
}

server <- shinyServer(function(input, output) {
})

shinyApp(ui = ui(), server = server)
```

I already tried to implement [the semantic sticky example](https://semantic-ui.com/modules/sticky.html), but it didn't work out. So does someone know how to approach this?

Thanks in advance!
Simon

**Comment by dokato** [comment]
Thanks, @systats for reporting this. I'll take a look on how easy it is to achieve this.

**Comment by ajbodine** [comment]
It requires a little help from shinyjs, but it's not too bad. If you give your grid an id, (I just called it "page") and reference that as the context of the javascript, you should be set.

```R
library(shinyjs)
ui <- function() {
  shinyUI(
    semanticPage(
      div(class = "ui grid", id = "page",
        div(class ="row",
          div(class = "eight wide column",
            div(class = "ui segment",
              purrr::map(1:100, ~ br()),
              "End of the page ..."
            )
          ),
          div(class = "eight wide column",
            div(class = "ui fixed top sticky",
              div(class = "ui secondary segment",
                 "This is how you make it sticky!"
              )
            )
          )
        )  
      )
    )
  )
}

server <- shinyServer(function(input, output) {
  stickyJS <- "
    $(document).ready(function(){
      $('.ui.sticky')
        .sticky({
          context: '#page',
          pushing: false;
        });
    })
  "
  runjs(stickyJS)
})
````

**Comment by systats** [comment]
Well, that doesn't seem to be too complex. But of course thanks a lot for your contributions!
