### ISSUE TITLE
uirender doesn't show modal correctly

### ISSUE THREAD

**Issue by krystian8207** [Appsilon/shiny.semantic#94]
Knitting below code makes displaying modal all grey. The change happened around commit: `477343a87f5d6eccc73a34b1cbe76f5adf40de8f`

```
---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(shiny.semantic)
```\

```{r, echo=FALSE}
make_table_row <- function() {

    button_class <- "ui tiny button"
    
    onclick <- sprintf("$('#%s').modal('show');", "modal_id")
    modal <- 
      div(id = "modal_id", class = "ui longer test modal visible scrolling", 
          div(class = "header", tags$h5("Modal title")),
          div(class = "scrolling content",
              div(class = "description",
                  "Description"
              )
          )
      )

  tags$tr(
    tags$td(class = "left aligned",
            tags$h6("Title")
    ),
    tags$td(class = "center aligned",
            tagList(
              modal,
              tags$button(class = button_class, "Show", onclick = onclick)
            )
    )
  )
}

shiny.semantic::uirender(make_table_row(), width = "100%", height = "100%")
```\
```

**Comment by galachad** [comment]
In this case, the semantic library is not loaded.
The best solution to handle this issue is to create an output function for rmarkdown. The output function used in this example is `rmarkdown::html_document` we need to create a similar function in shiny.semantic.

The semantic functions are not loaded or are overwritten by bootstrap. The simplest solution is just loaded semantic in the file e.g.
```
<script src="https://d335w9rbwpvuxm.cloudfront.net/semantic.min.js"></script>
```

**Comment by galachad** [comment]
I have tested loading the dependencies in self-contained mode. Semantic CSS can't be handled by pandoc. We can create task to solve this issue but for now, it's possible only to load dependencies from an external sources.
