### ISSUE TITLE
Navbar in shiny.semantic?

### ISSUE THREAD

**Issue by cecilialee** [Appsilon/shiny.semantic#95]
I wonder how can I create the navbar showcased in your app with shiny.semantic?
It looks awesome and really useful.

Thanks!

![image](https://user-images.githubusercontent.com/8072787/43179910-d0c7f1a8-9007-11e8-9d75-7fc6c873c86a.png)

**Comment by emilmahler** [comment]
If you can't use the shiny.router package because you are running Shiny in Docker, how can you handle the href? In the shiny.semantic tabset you have the content input (e.g. content = my_page()), but that doesn't work with this example.
